import pandas as pd
df = pd.read_csv(r'data/sample_complaints.csv')
print("Columns:", df.columns.tolist())
print("Dtypes:", df.dtypes.to_dict())
print("Shape:", df.shape)
print("Head:")
print(df.head(3).to_string())
print("Statuses:", df['status'].unique().tolist())
print("Date range:", df['created_date'].min(), "to", df['created_date'].max())
print("Areas:", sorted(df['area'].unique().tolist()))
print("Categories:", sorted(df['category'].unique().tolist()))
