import pathlib

TARGET = pathlib.Path(r"C:\Users\adith\Documents\Complaint-Analytics-Dashboard\frontend\streamlit_app.py")

FULL_CODE = []
A = FULL_CODE.append

# ── IMPORTS ──
A('"""')
A('Complaint Analytics Dashboard - Streamlit Frontend')
A('Talks to the FastAPI backend at http://127.0.0.1:8000')
A('"""')
A('from __future__ import annotations')
A('')
A('from datetime import date, datetime')
A('')
A('import pandas as pd')
A('import plotly.express as px')
A('import plotly.graph_objects as go')
A('import requests')
A('import streamlit as st')
A('')
A('# ─────────────────────────────────────────────')
A('# CONFIG')
A('# ─────────────────────────────────────────────')
A('API_URL        = "http://127.0.0.1:8000"')
A('ADMIN_PASSWORD = "admin123"')
A('')
A('st.set_page_config(')
A('    page_title="Complaint Analytics Dashboard",')
A('    page_icon="\U0001f4ca",')
A('    layout="wide",')
A('    initial_sidebar_state="expanded",')
A(')')
A('')
A('# ─────────────────────────────────────────────')
A('# HELPER FUNCTIONS')
A('# ─────────────────────────────────────────────')
A('def status_badge(status: str) -> str:')
A('    """Return colored HTML badge for status."""')
A('    colors = {"Closed": "#10b981", "In Progress": "#f59e0b", "Pending": "#ef4444"}')
A('    color = colors.get(status, "#6b7280")')
A('    return (')
A('        f\'<span style="background:{color};color:white;padding:4px 12px;\'')
A('        f\'border-radius:12px;font-size:0.75rem;font-weight:600;">{status}</span>\'')
A('    )')
A('')
A('')
A('def priority_badge(priority: str) -> str:')
A('    """Return colored HTML badge for priority."""')
A('    colors = {"High": "#dc2626", "Medium": "#f59e0b", "Low": "#10b981"}')
A('    color = colors.get(priority, "#6b7280")')
A('    return (')
A('        f\'<span style="background:{color};color:white;padding:4px 12px;\'')
A('        f\'border-radius:12px;font-size:0.75rem;font-weight:600;">{priority}</span>\'')
A('    )')
A('')
# ── CSS ──
A('# ─────────────────────────────────────────────')
A('# CSS (single st.markdown with all styles)')
A('# ─────────────────────────────────────────────')
A('st.markdown(')
A('    """')
A('    <style>')
A("    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');")
A('')
A("    html, body, [class*=\"css\"] { font-family: 'Inter', sans-serif; }")
A('')
A('    .stApp { background: #0b0f1a; color: #f1f5f9; }')
A('')
A('    .main .block-container {')
A('        padding-top: 1.5rem !important;')
A('        padding-left: 2rem !important;')
A('        padding-right: 2rem !important;')
A('        max-width: 100% !important;')
A('    }')
A('')
A('    section[data-testid="stSidebar"] {')
A('        background: linear-gradient(180deg, #0d1117 0%, #111827 100%);')
A('        border-right: 1px solid rgba(99,102,241,0.2);')
A('    }')
A('    section[data-testid="stSidebar"] * { color: #e2e8f0 !important; }')
A('    section[data-testid="stSidebar"] .stSelectbox label,')
A('    section[data-testid="stSidebar"] .stDateInput label {')
A('        color: #94a3b8 !important; font-size: 0.78rem !important;')
A('    }')
A('')
A('    .page-header {')
A('        background: linear-gradient(135deg, rgba(99,102,241,0.12) 0%, rgba(139,92,246,0.08) 100%);')
A('        border: 1px solid rgba(99,102,241,0.2);')
A('        border-radius: 20px;')
A('        padding: 24px 28px;')
A('        margin-bottom: 28px;')
A('    }')
A('    .page-header-title { font-size: 1.8rem; font-weight: 800; color: #f1f5f9; margin-bottom: 4px; }')
A('    .page-header-sub   { font-size: 0.85rem; color: #94a3b8; margin-bottom: 8px; }')
A('    .header-badges { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 10px; }')
A('    .header-badge {')
A('        background: rgba(99,102,241,0.2);')
A('        border: 1px solid rgba(99,102,241,0.4);')
A('        border-radius: 50px;')
A('        padding: 4px 12px;')
A('        font-size: 0.72rem;')
A('        color: #a5b4fc;')
A('        font-weight: 600;')
A('        white-space: nowrap;')
A('    }')
A('')
A('    .kpi-grid {')
A('        display: grid;')
A('        grid-template-columns: repeat(5, 1fr);')
A('        gap: 12px;')
A('        margin-bottom: 28px;')
A('    }')
A('    .kpi-card {')
A('        background: linear-gradient(135deg, rgba(255,255,255,0.06) 0%, rgba(255,255,255,0.03) 100%);')
A('        border: 1px solid rgba(255,255,255,0.08);')
A('        border-radius: 16px;')
A('        padding: 18px 16px;')
A('        backdrop-filter: blur(16px);')
A('        box-shadow: 0 4px 20px rgba(0,0,0,0.4), inset 0 1px 0 rgba(255,255,255,0.06);')
A('        transition: transform .2s, box-shadow .2s;')
A('        position: relative;')
A('        overflow: hidden;')
A('        box-sizing: border-box;')
A('    }')
A("    .kpi-card::before {")
A("        content: '';")
A('        position: absolute;')
A('        top: 0; left: 0; right: 0;')
A('        height: 3px;')
A('        background: var(--accent, linear-gradient(90deg, #6366f1, #8b5cf6));')
A('        border-radius: 16px 16px 0 0;')
A('    }')
A('    .kpi-card:hover { transform: translateY(-3px); box-shadow: 0 8px 32px rgba(0,0,0,0.5); }')
A('    .kpi-icon  { font-size: 1.3rem; margin-bottom: 8px; display: block; }')
A('    .kpi-label { font-size: 0.68rem; color: #64748b; letter-spacing: .08em; text-transform: uppercase; font-weight: 600; display: block; }')
A('    .kpi-value { font-size: 1.75rem; font-weight: 800; line-height: 1.15; margin-top: 6px; display: block; }')
A('    .kpi-sub   { font-size: 0.68rem; color: #475569; margin-top: 6px; display: block; }')
A('')
A('    .glass {')
A('        background: linear-gradient(135deg, rgba(255,255,255,0.05) 0%, rgba(255,255,255,0.02) 100%);')
A('        border: 1px solid rgba(255,255,255,0.07);')
A('        border-radius: 18px;')
A('        padding: 20px 22px;')
A('        margin-bottom: 16px;')
A('        backdrop-filter: blur(12px);')
A('        box-shadow: 0 4px 24px rgba(0,0,0,0.3);')
A('        box-sizing: border-box;')
A('    }')
A('    .glass-accent {')
A('        border-color: rgba(99,102,241,0.2);')
A('        box-shadow: 0 4px 24px rgba(99,102,241,0.08);')
A('    }')
A('')
A('    .section-title {')
A('        font-size: 0.88rem;')
A('        font-weight: 700;')
A('        color: #c7d2fe;')
A('        margin-bottom: 14px;')
A('        display: flex;')
A('        align-items: center;')
A('        gap: 8px;')
A('        padding-bottom: 10px;')
A('        border-bottom: 1px solid rgba(255,255,255,0.06);')
A('    }')
A('    .section-title-icon {')
A('        background: rgba(99,102,241,0.2);')
A('        border-radius: 6px;')
A('        padding: 3px 7px;')
A('        font-size: 0.85rem;')
A('        flex-shrink: 0;')
A('    }')
A('')
A('    [data-testid="column"] { padding: 0 6px !important; }')
A('    [data-testid="column"]:first-child { padding-left: 0 !important; }')
A('    [data-testid="column"]:last-child  { padding-right: 0 !important; }')
A('    [data-testid="stHorizontalBlock"] { align-items: stretch; gap: 12px; }')
A('')
A('    .stTabs [data-baseweb="tab-list"] {')
A('        background: rgba(255,255,255,0.04);')
A('        border-radius: 12px;')
A('        padding: 4px;')
A('        gap: 4px;')
A('        border: 1px solid rgba(255,255,255,0.06);')
A('    }')
A('    .stTabs [data-baseweb="tab"] {')
A('        border-radius: 8px;')
A('        color: #94a3b8;')
A('        font-weight: 600;')
A('        font-size: 0.85rem;')
A('        padding: 8px 18px;')
A('    }')
A('    .stTabs [aria-selected="true"] {')
A('        background: linear-gradient(135deg, #6366f1, #8b5cf6) !important;')
A('        color: white !important;')
A('    }')
A('    .stTabs [data-baseweb="tab-panel"] { padding-top: 20px; }')
A('')
A('    .stButton > button {')
A('        background: linear-gradient(135deg, #6366f1, #8b5cf6);')
A('        color: white;')
A('        border: none;')
A('        border-radius: 10px;')
A('        font-weight: 600;')
A('        font-size: 0.85rem;')
A('        padding: 10px 22px;')
A('        transition: all .2s;')
A('        box-shadow: 0 4px 12px rgba(99,102,241,0.3);')
A('    }')
A('    .stButton > button:hover {')
A('        opacity: 0.9;')
A('        transform: translateY(-1px);')
A('        box-shadow: 0 6px 16px rgba(99,102,241,0.4);')
A('    }')
A('')
A('    .stTextInput input, .stTextArea textarea, .stSelectbox select {')
A('        background: rgba(255,255,255,0.05) !important;')
A('        border: 1px solid rgba(255,255,255,0.1) !important;')
A('        border-radius: 10px !important;')
A('        color: #f1f5f9 !important;')
A('    }')
A('    .stTextInput input:focus, .stTextArea textarea:focus {')
A('        border-color: rgba(99,102,241,0.5) !important;')
A('        box-shadow: 0 0 0 3px rgba(99,102,241,0.15) !important;')
A('    }')
A('')
A('    .stDataFrame { border-radius: 12px; overflow: hidden; }')
A('    div[data-testid="metric-container"] {')
A('        background: rgba(255,255,255,0.04);')
A('        border: 1px solid rgba(255,255,255,0.07);')
A('        border-radius: 12px;')
A('        padding: 14px;')
A('    }')
A('')
A('    .stSuccess, .stError, .stWarning, .stInfo { border-radius: 10px; }')
A('    hr { border-color: rgba(255,255,255,0.06) !important; }')
A('')
A('    ::-webkit-scrollbar { width: 6px; height: 6px; }')
A('    ::-webkit-scrollbar-track { background: rgba(255,255,255,0.02); }')
A('    ::-webkit-scrollbar-thumb { background: rgba(99,102,241,0.4); border-radius: 3px; }')
A('')
A('    .badge { display: inline-block; padding: 3px 10px; border-radius: 20px; font-size: 0.72rem; font-weight: 700; letter-spacing: 0.04em; }')
A('    .badge-closed     { background: rgba(16,185,129,0.2); color: #6ee7b7; border: 1px solid rgba(16,185,129,0.3); }')
A('    .badge-inprogress { background: rgba(245,158,11,0.2); color: #fcd34d; border: 1px solid rgba(245,158,11,0.3); }')
A('    .badge-pending    { background: rgba(239,68,68,0.2);  color: #fca5a5; border: 1px solid rgba(239,68,68,0.3); }')
A('    .badge-high       { background: rgba(220,38,38,0.2);  color: #fca5a5; border: 1px solid rgba(220,38,38,0.3); }')
A('    .badge-medium     { background: rgba(245,158,11,0.2); color: #fcd34d; border: 1px solid rgba(245,158,11,0.3); }')
A('    .badge-low        { background: rgba(16,185,129,0.2); color: #6ee7b7; border: 1px solid rgba(16,185,129,0.3); }')
A('')
A('    .progress-bar-wrap { background: rgba(255,255,255,0.06); border-radius: 99px; height: 6px; overflow: hidden; margin-top: 10px; }')
A('    .progress-bar-fill { height: 100%; border-radius: 99px; }')
A('')
A('    .export-btn {')
A('        display: inline-flex; align-items: center; gap: 8px;')
A('        background: linear-gradient(135deg, #6366f1, #8b5cf6);')
A('        color: white; border: none; border-radius: 10px;')
A('        padding: 9px 20px; font-weight: 600; font-size: 0.85rem;')
A('        cursor: pointer; text-decoration: none;')
A('        box-shadow: 0 4px 12px rgba(99,102,241,0.3);')
A('        transition: all .2s;')
A('    }')
A('    .export-btn:hover { opacity: 0.9; transform: translateY(-1px); color: white; }')
A('    </style>')
A('    """,')
A('    unsafe_allow_html=True,')
A(')')
A('')
